dataset:
  download_format: yolov8
  project_name: code-detection-aavzz
  location: datasets/code-detection-with-validation__merged-all
  version_number: 2
  data_yaml: datasets/code-detection-with-validation__merged-all/dataE1v2.yaml
training:
  project: results/
  name: syntheticPCBE1v2
  task: detect
  mode: train
  model: yolov10s.pt
  pretrained: true
  epochs: 201
  time: null
  patience: 50
  batch: 16
  imgsz: 640
  save: true
  save_period: 10
  cache: false
  device: -1
  workers: 16
  exist_ok: false
  optimizer: auto
  verbose: true
  seed: 0
  deterministic: true
  single_cls: true
  rect: false
  cos_lr: false
  close_mosaic: 10
  resume: false
  amp: true
  fraction: 1.0
  profile: false
  freeze: null
  multi_scale: false
  overlap_mask: true
  mask_ratio: 4
  dropout: 0.0
  val: true
  split: val
  save_json: false
  conf: 0.35
  iou: 0.5
  max_det: 200
  half: true
  dnn: false
  plots: true
  source: null
  vid_stride: 1
  stream_buffer: false
  visualize: true
  augment: false
  agnostic_nms: false
  classes: null
  retina_masks: false
  embed: null
  show: false
  save_frames: false
  save_txt: true
  save_conf: true
  save_crop: false
  show_labels: true
  show_conf: true
  show_boxes: true
  line_width: null
  format: torchscript
  keras: false
  optimize: false
  int8: false
  dynamic: false
  simplify: true
  opset: null
  workspace: null
  nms: false
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  dfl: 1.5
  pose: 12.0
  kobj: 2.0
  nbs: 64
  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.75
  degrees: 180.0
  translate: 0.2
  scale: 0.5
  shear: 10.0
  perspective: 0.001
  flipud: 0.75
  fliplr: 0.75
  bgr: 0.0
  mosaic: 0.75
  mixup: 0.75
  cutmix: 0.75
  copy_paste: 0.0
  copy_paste_mode: flip
  auto_augment: null
  erasing: 0.75
  cfg: null
  tracker: botsort.yaml
